language: node_js
node_js:
  - 8
sudo: false

after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info || echo "Could not upload code coverage to CodeClimate"
